### ISSUE TITLE
libc++_shared.so not found in games

### ISSUE THREAD

**Issue by aubade** [JohnnyonFlame/droidports#9]
I'm trying to get this running on my RasPi 3B, and none of the games I've tried it with (a fresh AM2r 1.5.5 created from AM2r loader, an older AM2R 1.5.2 downloaded from the internet, and Maldita Castilla for the Ouya) seem to have any libc++_shared.so files, so gmloader will not run them.

**Comment by JohnnyonFlame** [comment]
Please refer to this discussion: https://github.com/Exarkuniv/RetroPie-Extra/pull/161#issuecomment-1668655278

**Comment by aubade** [comment]
That's good to know!

Though, for what it's worth the workaround I did was to manually comment out the part in the code that extracts the libc++_shared.so file and the game then worked just fine, so it might be worth not erroring out if it can't find the file in the apk?

**Comment by JohnnyonFlame** [comment]
> That's good to know!
> 
> Though, for what it's worth the workaround I did was to manually comment out the part in the code that extracts the libc++_shared.so file and the game then worked just fine, so it might be worth not erroring out if it can't find the file in the apk?

This is only okay for very old gamemaker titles, newer runners want more and more libc++ symbols, some which are incredibly non-trivial to implement, hence why it now requires the library.

The correct fix here is just packaging libc++ with other basic runtime libraries, which is what gmloader-next will do when it's public.

Closing this since you have found a solution, cheers and have fun.
